### ISSUE TITLE
No more colors

### ISSUE THREAD

**Issue by eolianoe** [geier/khal#113]
The colours seems to have disappeared from khal and ikhal after the commit cabaf5af9be050456fb7b6241cd7d59b3df2b6fd (there are present in this commit but not in the commit 6bbe10a2218d2c42b2b8d80a72f4171f6f1e6ca5 and the others after).

Tested with different shells (bash,zsh) and different console (urxvt,xterm).

**Comment by geier** [comment]
@untitaker is this ready now?

**Comment by untitaker** [comment]
Fixed.

**Comment by untitaker** [comment]
Also verified that the test fails properly if I braak khal's color attributes in `khal/khalendar/khalendar.py`.

**Comment by geier** [comment]
Thanks! :dancer:
