### ISSUE TITLE
Events created with "khal new" are one hour off when shown in EGroupware or Android

### ISSUE THREAD

**Issue by robodendron** [geier/khal#123]
I'm running into issues with Khal from Git (latest snapshot, f53b9c3), our EGroupware 1.8.005 server, and DST settings.

When creating an event with `khal new` which happens during DST, the time shown in the EGroupware calendar is always an hour later than what I've entered: e.g. `khal new 25.10. 8:00 10:00` results in an EGroupware entry that starts at 9:00 and ends at 11:00.

In contrast, when creating an event which happens *post-DST*, the time shown in EGroupware is an hour *earlier* than what I entered: `khal new 30.10. 8:00 10:00` results in an EGroupware entry starting at 7:00 and ending at 9:00.

[Here](https://gist.github.com/robodendron/24f3e33b28a14ae8c7eb) is a Gist with a number of iCalendar files that exhibit this behavior:

* `khal--during-dst.ics` and `khal--post-dst.ics` were created using khal and exhibit the behavior described above.
* `khal--during-dst--changed-in-eg.ics` and `khal--post-dst--changed-in-eg.ics` refer to the same events as the two previous files, but the times were manually corrected in EGroupware.
* `eg--during-dst.ics` and `eg--post-dst.ics` are events created from within EGroupware.
* `khal.conf` is my khal configuration. The timezones are set explicitly in order to eliminate `tzlocal` as the potential error source, otherwise nothing out of the ordinary here.

Interestingly, all times are displayed correctly in khal itself—even after I've manually corrected them in EGroupware. I'm not sure whether this is an issue with khal or with our EGroupware server.

In any case, thanks for a cool program. :)

**Comment by geier** [comment]
I'll close this now for lack of activity, if anyone has this bug again, please reopen or file a new one.
