### ISSUE TITLE
Return events occuring now (or at a given time)

### ISSUE THREAD

**Issue by mhyzon** [geier/khal#125]
Possibly as an enhancement to the agenda mode, like if you specify a longdatetime format.  Return only events happening at that day & time.  IE all day events or events where start <= longdatetime < end

**Comment by geier** [comment]
What name would you imagine for that command? Some ideas of the top of my head:

* khal now [datetime]
* khal at [now]

**Comment by mhyzon** [comment]
Yeah, khal at [datetime] would make sense.

As a bit of background, I'm trying to replace a schedule that is used by automation script.  The schedule format is currently a custom yaml file.  A standard "ical" calendar would be easier for other to modify and view using standard calendaring tools.

I couldn't for the life of me find a reasonable shell-friendly or python library without duplicating pretty much everything you're doing in khal already, and I am not a great programmer, just a sysadmin. :)

**Comment by iranzo** [comment]
Imho 'now' will it make clear for the 'What's next?' and the ability to specify the datetime would allow to define what 'now' is for that query.

**Comment by untitaker** [comment]
How about:

* ``khat at now`` for events occuring right now.
* ``khal at [dt]`` for events occuring at a given time.

**Comment by geier** [comment]
What about all day events? Do you want to see them to? Should we make that configurable?

**Comment by untitaker** [comment]
current behavior (showing them) seems fine.

**Comment by geier** [comment]
fixed with a8b21fbe9173c7f775770aea14e2465be838a315 and following
