### ISSUE TITLE
Typo in doc/source/Makefile

### ISSUE THREAD

**Issue by mbaldessari** [geier/khal#155]
Hi Christian,

doc/source/Makefile has this:
doc/source/Makefile:configspec.rst: ../../../khal-0.3.1/khal/settings/khal.spec

It will need to be changed to 0.4.0

Thanks a lot ;)
Michele

**Comment by untitaker** [comment]
``master`` doesn't have this:

    configspec.rst: ../../../khal/khal/settings/khal.spec

And I can't see that it ever did. Where do you have this version from? oO

**Comment by mbaldessari** [comment]
Meh, I just took the release tgz (am building rpms), and the build failed because of that. 
Hohum, odd, likely screwup on my part then (/me puts down the smokepipe)
