### ISSUE TITLE
astimezone() argument 1 must be datetime.tzinfo, not None

### ISSUE THREAD

**Issue by mbaldessari** [geier/khal#158]
I haven't seen a similar issue reported, so here we go:
With khal-0.4.0 I now have most of the recurring/odd calendar entries working (thanks!). There are
a couple of those that error out with the following:
Unknown exception happened.
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/khal/khalendar/khalendar.py", line 175, in _update_vevent
    self._dbtool.update(event.raw, href=href, etag=etag)
  File "/usr/lib/python2.7/site-packages/khal/khalendar/backend.py", line 253, in update
    self._update_impl(vevent, href, etag)
  File "/usr/lib/python2.7/site-packages/khal/khalendar/backend.py", line 280, in _update_impl
    dtstartend = aux.expand(vevent, self.locale['default_timezone'], href)
  File "/usr/lib/python2.7/site-packages/khal/khalendar/aux.py", line 101, in expand
    exdates = localize_strip_tz(exdates, events_tz)
  File "/usr/lib/python2.7/site-packages/khal/khalendar/aux.py", line 165, in localize_strip_tz
    one_date = one_date.astimezone(timezone)
TypeError: astimezone() argument 1 must be datetime.tzinfo, not None
warning: Skipping work/5624b646-ba12-4dbd-ba9f-8d66319b0776.ics: astimezone() argument 1 must be datetime.tzinfo, not None
warning: This event will not be available in khal.

I will clean up the ics file above and upload it here.

Thanks again for khal, it's shaping up very nicely!

**Comment by mbaldessari** [comment]
I've put a stripped down ics where the error occurs here: http://acksyn.org/files/tmp/error-ast-no-desc-attend.isc (I removed DESCRIPTION, ATTENDEE and PRIORITY with a quick sed rule, hope that is ok)

**Comment by geier** [comment]
Thank you for the report, I'll have a closer look asap (but probably not before tomorrow).

**Comment by untitaker** [comment]
There don't seem to be any ``END:VALARM`` lines, making this a nested list of valarms. Did your sed rule rip that out?

**Comment by untitaker** [comment]
Also a lot of stuff is kinda chopped off so this version doesn't even parse correctly in khal. Could you give a minimal or censored variant with which khal is crashing like in your case?

**Comment by mbaldessari** [comment]
Let me double-check if I stripped out too much stuff, it looked sane at first glance, but maybe I missed out something

**Comment by mbaldessari** [comment]
Alright, hopefully second time is bliss: http://acksyn.org/files/tmp/error-ast-no-desc-attend-v2.isc

**Comment by untitaker** [comment]
For some reason your timezone isn't recognized. Minimal testcase: https://gist.github.com/untitaker/f52c13a9b9ebb752400d

**Comment by geier** [comment]
alright, I found the problem:  DTSTART is localized, but the EXDATEs are not (but in Zulu time). This is easy to fix, but a problem may arise. As in your example, khal does not understand the timezone (because icalendar does not yet, see [this PR](https://github.com/collective/icalendar/pull/154/), it therefore applies the configured `default_timezone`. If `default_timezone` is not the proper timezone for this event, the EXDATEs will not be removed (but I guess the wrong offset is the bigger problem anyway).
