### ISSUE TITLE
colouring day number if it has event

### ISSUE THREAD

**Issue by quite** [geier/khal#163]
For me, day numbers (interactive or otherwise) does not have a special colour even if there is a calendar event on that day. Only today and currently selected day has a colour. Is this correct, or is there something wrong with my system?

**Comment by untitaker** [comment]
That's correct.

**Comment by geier** [comment]
Do you mean in ikhal or in khal? If it is khal, this is a duplicate of #89

**Comment by untitaker** [comment]
Ah, let's use one ticket for both.

**Comment by quite** [comment]
Correct.
