### ISSUE TITLE
ikhal editor: Don't make the user scroll down to save

### ISSUE THREAD

**Issue by untitaker** [geier/khal#165]
From #160 

Introduce some Ctrl-Shortcut maybe?

**Comment by geier** [comment]
ctrl-s perhaps? even though it kind of feels weird.

**Comment by untitaker** [comment]
Ctrl-S freezes the shell unless you turn it off explicitly.

**Comment by geier** [comment]
I thought this was only the case in virtual consoles, but you are right.

**Comment by untitaker** [comment]
I mean you *can* turn that off, so it might make sense to *also* bind to that shortcut.

We could do it like vim, and bind the save key to a letter. That would require hitting `Enter` to edit textfields.

**Comment by hobarrera** [comment]
<kbd>Ctrl</kbd> + <kbd>Enter</kbd>?

**Comment by untitaker** [comment]
Not sure if that one can be detected reliably (i.e. distringuished from just Enter), but I'd be fine with it.

**Comment by geier** [comment]
`ctrl` + `Enter` doesn't work with my setup, `alt` + `Enter` does

**Comment by geier** [comment]
fixed with 40ca1900ac97ba58e79220e50d6b15b5569, but ideas for more reasonable default settings are still welcome.
