### ISSUE TITLE
Timezone oddities

### ISSUE THREAD

**Issue by mbaldessari** [geier/khal#170]
Hi Christian,

I am not 100% sure where the issue lies. Basically Zimbra shows me a calendar entry at 15:00,
whereas khal shows it at 14:00. This is the ics entry (attendees stripped out):
```
BEGIN:VCALENDAR
VERSION:2.0
PRODID:Zimbra-Calendar-Provider
BEGIN:VTIMEZONE
TZID:GMT/+01.00
BEGIN:STANDARD
DTSTART:16010101T010000
TZOFFSETTO:-0000
TZOFFSETFROM:+0100
RRULE:FREQ=YEARLY;INTERVAL=1;BYMONTH=10;BYDAY=-1SU;WKST=MO
END:STANDARD
BEGIN:DAYLIGHT
DTSTART:16010101T020000
TZOFFSETTO:+0100
TZOFFSETFROM:-0000
RRULE:FREQ=YEARLY;INTERVAL=1;BYMONTH=3;BYDAY=-1SU;WKST=MO
END:DAYLIGHT
END:VTIMEZONE
BEGIN:VEVENT
UID:bfcf13fe-3dc5-48ec-9fa0-b30bff5789dd
RRULE:FREQ=WEEKLY;INTERVAL=2;BYDAY=FR
SUMMARY:Call 
DESCRIPTION:Call 
ORGANIZER;CN=Michele Baldessari:mailto:michele@acksyn.org
DTSTART;TZID="GMT/+01.00":20150227T140000
DTEND;TZID="GMT/+01.00":20150227T143000
STATUS:CONFIRMED
CLASS:PUBLIC
TRANSP:OPAQUE
LAST-MODIFIED:20150217T071347Z
DTSTAMP:20150217T071347Z
SEQUENCE:5
BEGIN:VALARM
ACTION:DISPLAY
TRIGGER;RELATED=START:-PT5M
DESCRIPTION:Reminder
END:VALARM
END:VEVENT
END:VCALENDAR
```

In my config I do have:
```
[locale]
local_timezone= Europe/Berlin
default_timezone= Europe/Berlin
```

Am I missing something completely obvious here or is this another case of Zimbra funkiness?

Thanks and regards,
Michele

**Comment by geier** [comment]
The above defined timezone is not equivalent to `Europe/Berlin` as it has an offset off zero or one hours to GMT (depending if it is daylight saving time), but `Europe/Berlin` has one or two hours offset.

Here is a valid Europe/Berlin example: http://tzurl.org/zoneinfo/Europe/Berlin.ics

**Comment by mbaldessari** [comment]
Is this a cockup on my part or is it Zimbra being dense again? In my preferences on Zimbra I have timezone "GMT +1:00 Amsterdan, Berlin, Bern, Rome, ..." selected. Am I supposed to change it to something else or is this issue related to the fact ths this ics has non Olson DB Timezone?

**Comment by geier** [comment]
to me it looks like a proper bug on zimbra's side. I can look into it next week.

**Comment by geier** [comment]
Do you know which version of zimbra this was created with?

**Comment by mbaldessari** [comment]
So the version I currently have is: Zimbra 8.0.6_GA_5922 (build 20131203103753)
It could be that the above calendar entry was created with an older version (of that I am not sure and have no means of verifying)

**Comment by geier** [comment]
It looks like current versions of Zimbra produce valid VTIMEZONE components and I actually cannot find any hint that they were once broken.

The good news is, if you update [icalendar](https://github.com/collective/icalendar), khal will (in)correctly show this event starting at 15:00.

**Comment by mbaldessari** [comment]
Thanks so much! I confirm that updating to 3.9.0 fixes this and I see the event at 15:00 instead of 14:00
