### ISSUE TITLE
khal is extremely slow

### ISSUE THREAD

**Issue by hobarrera** [geier/khal#172]
With only three events, khal is extremely slow.

I read it indexes some things the first time it's run, so I timed the second run, and still:

```
$ khal && time khal
...
khal  1.07s user 0.06s system 99% cpu 1.127 total
```

**Comment by thomwiggers** [comment]
I'm also experiencing this:

`khal  0.83s user 0.08s system 3% cpu 25.923 total`

**Comment by geier** [comment]
did you try this: https://github.com/geier/khal/issues/79#issuecomment-44614108 ?

**Comment by hobarrera** [comment]
Doesn't seem applicable to me:

```
$ sudo pip2 unzip pytz          
DEPRECATION: 'pip zip' and 'pip unzip` are deprecated, and will be removed in a future release.
The module pytz (in /usr/lib/python2.7/site-packages/pytz) is not a zip file; cannot be unzipped
```

Effectively, `/usr/lib/python2.7/site-packages/pytz`is a directory (with ~600 children).

Oh, also, I upgraded to latest from git, and issue is also present.

**Comment by thomwiggers** [comment]
The test case in the FAQ only takes half a second for me so I don't think that's the issue. 

On 13 March 2015 13:33:26 CET, Christian Geier <notifications@github.com> wrote:
>did you try this:
>https://github.com/geier/khal/issues/79#issuecomment-44614108 ?
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/geier/khal/issues/172#issuecomment-78951060

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by geier** [comment]
Something really is not right than, especially for @thomwiggers example (25s). 
You could really help by running:

    python -mcProfile -o khal.profile `which khal agenda`

(this will create a file khal.profile with all the running information) and send me the output file (khal.profile) via mail (contact@lostpackets.de).

**Comment by untitaker** [comment]
How's disk activity during startup? Maybe khal sees that the mtime of the directory changes all the time.

**Comment by untitaker** [comment]
To clarify: `touch`ing all calendars before starting khal significantly slows down startup for me. Maybe this somehow applies to your case?

**Comment by hobarrera** [comment]
> To clarify: touching all calendars before starting khal significantly slows down startup for me. Maybe this somehow applies to your case?

It's unlikely that something touches the files so quickly, since I'm running "khal && time khal". All I have refering to that directory is vdirsyncer cronned every few minutes, it can't have run *exactly* at the same time every time I ran the test.

**Comment by hobarrera** [comment]
Te above command did not work for me :(

```
$ python2 -mcProfile -o khal.profile `which khal agenda`
CRITICAL:root:"not" does not look like a valid date
```

(I had to run python2, since khal does to run with python3).

**Comment by hobarrera** [comment]
Duh, proper command is:

    python2 -mcProfile -o khal.profile `which khal` agenda

The backtick notation slip past my - I'd mostly seen `$(which khal)` up to now .;)

Anyway: http://files.barrera.io/khal/khal.profile

**Comment by geier** [comment]
@thomwiggers' problems were fixed, it was due to some keyring issue (khal importing vdirsyncer in turn importing keyring).

@hobarrera in your case it looks like the import of requests takes up most of the time. Could you run `time python -c 'import requests'` ?

**Comment by hobarrera** [comment]
```
▶ time python2 -c 'import requests'
python2 -c 'import requests'  0.93s user 0.03s system 98% cpu 0.978 total
```

**Comment by geier** [comment]
there is your problem then, although there is no need to import requests at all when running khal...

**Comment by geier** [comment]
@untitaker is it possible to reorganize vdirsyncer in a sensible way so that importing vdirsyncer.filesystem.FilesystemStorage` does not trigger an import of request and keyring?

**Comment by untitaker** [comment]
I'm willing to do this, but at this point it's worth considering whether

* FilesystemStorage should be its own package
* khal should simply vendor it
* it even makes sense for khal to depend on vdirsyncer for such a little amount of code

**Comment by untitaker** [comment]
Just pushed a commit to master that fixes this.

**Comment by untitaker** [comment]
@hobarrera Khal's startup time should've dropped now.

**Comment by geier** [comment]
@untitaker thanks this (but this really wasn't a request for immediate action, we probably should think about your discussion points)

**Comment by untitaker** [comment]
I've been wanting to do the restructuring for a long time anyway.

**Comment by hobarrera** [comment]
Built latest from master:

    khal  1.13s user 0.07s system 99% cpu 1.198 total

**Comment by hobarrera** [comment]
Is this supposed to still work?

```
▶ python2 -mcProfile -o khal.profile `which khal` agenda  
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/lib/python2.7/cProfile.py", line 199, in <module>
    main()
  File "/usr/lib/python2.7/cProfile.py", line 192, in main
    runctx(code, globs, None, options.outfile, options.sort)
  File "/usr/lib/python2.7/cProfile.py", line 49, in runctx
    prof = prof.runctx(statement, globals, locals)
  File "/usr/lib/python2.7/cProfile.py", line 140, in runctx
    exec cmd in globals, locals
  File "/usr/bin/khal", line 9, in <module>
    load_entry_point('khal===0.5.0.dev-107-g28ed8d9-dirty', 'console_scripts', 'khal')()
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 546, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 539, in get_distribution
    dist = get_provider(dist)
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 419, in get_provider
    return working_set.find(moduleOrReq) or require(str(moduleOrReq))[0]
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 699, in find
    raise VersionConflict(dist, req)
pkg_resources.VersionConflict: (khal 0.5.0.dev-76-g3b5288b-dirty (/usr/lib/python2.7/site-packages/khal-0.5.0.dev_76_g3b5288b_dirty-py2.7.egg), Requirement.parse('khal===0.5.0.dev-107-g28ed8d9-dirty'))
```

**Comment by untitaker** [comment]
Try executing `pip uninstall khal` multiple times. I sometimes end up with the same package being in the pythonpath multiple times, and this usually fixes it.

**Comment by hobarrera** [comment]
> Try executing pip uninstall khal multiple times. I sometimes end up with the same package being in the pythonpath multiple times, and this usually fixes it.

Indeed, I actually had quite a mess, and I did that, plus `find /usr -iname "*khal*"` to make sure nothing was left behind.

After cleaning up and re-installing the latest from git:

    ▶ khal && time khal
    ...
    khal  1.13s user 0.05s system 99% cpu 1.190 total

**Comment by untitaker** [comment]
Hmm, did you update both khal and vdirsyncer?

**Comment by hobarrera** [comment]
Updating vdirsyncer showed improvements:

    khal  0.23s user 0.03s system 98% cpu 0.258 total

Thanks!

**Comment by hobarrera** [comment]
I still wonder why my laptop has lower times with vdirsyncer-stable (0.4.4):

    khal  0.20s user 0.01s system 97% cpu 0.217 total

Could HDD vs SDD be the cause for the entire difference?

**Comment by untitaker** [comment]
You're welcome!

@geier Thinking about extracting filesystem-storage, I'm not sure if I want the current API to be considered stable -- I probably have to bend it for some performance improvements.

**Comment by untitaker** [comment]
@hobarrera SSD probably makes a lot of difference, but it'd be surprising if vdirsyncer-git doesn't show improvements (even if small ones).

**Comment by hobarrera** [comment]
Yup, it did:

    khal  0.16s user 0.01s system 97% cpu 0.177 total

Thanks again.

**Comment by geier** [comment]
@hobarrera the profile you uploaded showed that importing requests took about 90% of the time. I don't think this is normal and there probably is some underlying issue with requests.

A nice way to look at these profile is via [runsnakerun](http://www.vrplumber.com/programming/runsnakerun/), just call `runsnake khal.profile` and you can explore the runtime (of the functions called in this case).

@untitaker don't really know if it is really needed (and if we do need another package), but I'm fine with however you decide.
