### ISSUE TITLE
Creating recurring events

### ISSUE THREAD

**Issue by hobarrera** [geier/khal#173]
The UI (eg: ikhal) states that edition recurring events is not supported.

I looked at the cli usage, and no mention of how to create them via cli is present either.
Is there something missing regarding the cli usage, or is the creation of recurring events impossible via any interface?

Thanks.

**Comment by geier** [comment]
you can create recurring events with *khal new*'s `-r` option (have a look at the help text *khal new --help*), e.g.: `khal new -r weekly 16:00 Weekly meeting` .

Looks like the docs need some improvement.

**Comment by hobarrera** [comment]
> you can create recurring events with khal new's -r option (have a look at the help text khal new --help), e.g.: khal new -r weekly 16:00 Weekly meeting .

Oh, thanks. Much like lots of the rest of my noise today, this was due to me not running the latest from git, hehe.

What's also missing is a `-until`, which is kinda important to avoid infinitely repeating events.

> Looks like the docs need some improvement.

Yup. If I manage to get the time, I'll see if I can help a bit.
