### ISSUE TITLE
use setuptools_scm

### ISSUE THREAD

**Issue by geier** [geier/khal#182]
[setuptools_scm](https://pypi.python.org/pypi/setuptools_scm) this should let us remove some custom code. I want to wait for the next release though.

**Comment by untitaker** [comment]
What is missing from the current release?

**Comment by geier** [comment]
Cannot remember really, just remember Ronny telling me about this and that coming with the next release.

**Comment by geier** [comment]
fixed with 886a3545307d6058b410f342e314

**Comment by hobarrera** [comment]
I have to say, setuptools_scm is rather confusing on it's versioning scheme. Pre-release versions are actually *larger* than the release that follows them.

IMHO, if we make 3 commits on top of version 0.5, it's 0.5+3, *not* 0.6+3 (which is the what setuptools_scm calls "distance").

**Comment by geier** [comment]
I actually don't like calling it 0.6+3, that kind of suggests that 0.6 was already released. That's why before we had `0.6.0.dev-3-gaa809e7`, but I'm just happy to see some pretty hacky code *outsourced*.

**Comment by untitaker** [comment]
According to a PEP (https://www.python.org/dev/peps/pep-0440/#local-version-identifiers), the `+`-part has to semantic meaning. I think if setuptools-scm didn't bump the version number for post-releases, `0.5+asdf` would be equal to `0.5` and pip would avoid to upgrade even if necessary. That's speculation on my part though.

Note that setuptools-scm's README mentions an upcoming change in the versioning scheme.
