### ISSUE TITLE
Review usage of unicode_literals

### ISSUE THREAD

**Issue by untitaker** [geier/khal#189]
See https://github.com/geier/khal/pull/187

**Comment by geier** [comment]
I'm with hobarrera on this, I don't have a problem with unicode_literals and haven't seen them brake something yet.

**Comment by untitaker** [comment]
Click will warn if unicode literals are used: https://github.com/mitsuhiko/click/commit/5f337705f68bdfa66d7c7a9fe7fc5d6bfd48db94

**Comment by untitaker** [comment]
See also: https://github.com/PythonCharmers/python-future/issues/22

**Comment by geier** [comment]
I guess we'll have to obey than.

**Comment by geier** [comment]
turns out you were right all along :-o
the idiotic decode in 8b25e5fc9eb3f70bb7b3904f16f0824ccb4192ec is only needed because of the unicode literals.

**Comment by hobarrera** [comment]
From PythonCharmers/python-future#22:

> Only a very low number of people are using Python 3.2 or older

I don't agree with this. Python 2.7 is still quite popular, probably the default for > 50% of the users.

---

While I don't really like how the code looks after these changes, I guess functionality is more important than aesthetics, so I won't argue on this further. :)

**Comment by untitaker** [comment]
This is only talking about Python 3 versions.

**Comment by geier** [comment]
I'm not a fan of the look either :( I'd love to drop python 2 support all along.

**Comment by hobarrera** [comment]
> I'm not a fan of the look either :( I'd love to drop python 2 support all along.

+1 on this. Also getting rid of compat+six. However, we really need to know if it's possible for downstream packages to update to py3 (maybe the entire dependency tree is missing from many distributions?).

We could open a separate issue and open this for discussion with downstream packagers and users.

**Comment by untitaker** [comment]
It's unlikely that Debian or some other LTS distros ship with 3.3+ as their
Python 3 package. However, khal depends on vdirsyncer, which requires 3.3+ or
2.7+.

Options:

* Remove vdirsyncer as dependency (good idea for other reasons too)
* Vdirsyncer drops Py2 support simultaneously.

**Comment by hobarrera** [comment]
Debian seems to include python3.3 on stable+ ([source](https://wiki.debian.org/Python)):

 * python3.4: stable, testing
 * python3.5: testing, unstable

Only oldstable seems to include python3 < 3.3 (it has 3.1, according to the above link). I *really* don't think we should limit ourselves because of Debian-oldstable.

However, the issue is if all other dependencies are available (otherwise the burden of packaging+maintaining would fall on the current khal maintainer, most likely).

Also: Does khal currently work with python3<3.3?

**Comment by untitaker** [comment]
>Also: Does khal currently work with python3<3.3?

Definetly doesn't, because of `u""`.

**Comment by untitaker** [comment]
Also bug-wise it's not ideal to use 3.3, a lot of stuff got ironed out in later versions.

**Comment by untitaker** [comment]
https://github.com/geier/khal/issues/302
