### ISSUE TITLE
Events that end on the same local date, but different GMT date are displayed oddly

### ISSUE THREAD

**Issue by hobarrera** [geier/khal#195]
```
$ khal search DAC
08.05.2015 10:30 - 08.05.2015 22:00: DAC Location:  Description:
15:30-17:30 2015-05-07: DAC Location:  Description:
...
```

As you can see by this output, the first event begins and ends on the same day, but it's displayed as a multiday event.

This is most likely because it ends on the next day, when working with GMT times (I'm UTC-0300).

**Comment by geier** [comment]
@hobarrera does this still apply?

**Comment by hobarrera** [comment]
Nope, at a quick glance, this is no longer an issue.

**Comment by geier** [comment]
Thanks, for reporting and checking.
