### ISSUE TITLE
Py3 tests fail in Travis

### ISSUE THREAD

**Issue by untitaker** [geier/khal#198]
See https://twitter.com/roguelynn/status/598951380016041984

I've put up a suggestion there which *theoretically* would help khal deal with ASCII-environments under Python 3, but having Click handle it with a clear error message seems much more sensible.

That's not an option under Travis, so I'd just manually set the envvars there.

**Comment by untitaker** [comment]
@geier I see you have a branch for this?

**Comment by geier** [comment]
Not really, I just tried to set the python 3 environment as an 'allowed
failure' (but failed).

Quoting Markus Unterwaditzer (2015-05-20 15:25:53)

**Comment by untitaker** [comment]
How about setting `$LANG` explicitly?

**Comment by geier** [comment]
At least setting it on travis doesn't seem to work.

**Comment by geier** [comment]
fixed with 44c13ce8cecae6b2ba2cd79
