### ISSUE TITLE
Improve Startup Speed of khal and ikhal

### ISSUE THREAD

**Issue by nedson** [geier/khal#204]
Any suggestions for speeding up khal? Using a raspberry pi...what can I do to speed up performance? Maybe this is wishful thinking using such a low spec machine.

**Comment by hobarrera** [comment]
khal keeps a cache of your calendars, so running `khal > /dev/null` after every external file update would guarantee that this cache is kept up-to-date.

The speed of your storage device will also make a difference. IIRC, the pi uses a slow SD card. Maybe mounting into a tmpfs  might make a difference.

**Comment by geier** [comment]
What you can do, is [send me a profile](https://github.com/geier/khal/issues/172#issuecomment-78962657), so I can have a look if there is anything that uses a lot of (startup) time.

**Comment by untitaker** [comment]
FWIW everything is inevitably slow on a RbPI 1, if you're actually doing work directly on the RbPI, I'd recommend looking for a faster machine.

**Comment by geier** [comment]
I'm gonna close this for lack of information.
