### ISSUE TITLE
Git not found

### ISSUE THREAD

**Issue by teto** [geier/khal#206]
With current HEAD (0e7045cec92e3370ed4e5fa8e4f8e41e1ec3f4de) on master:
```
$ python3 setup.py build
/home/teto/khal/version.py:35: UserWarning: WARNING: git not installed or failed to run
  warnings.warn("WARNING: git not installed or failed to run")
Traceback (most recent call last):
  File "setup.py", line 8, in <module>
    write_version()
  File "/home/teto/khal/version.py", line 45, in write_version
    with open(filename, 'w') as versionfile:
```

**Comment by geier** [comment]
I cannot reproduce this. Is there any more of that traceback? And is that directory writable?

**Comment by untitaker** [comment]
@teto Could you edit `version.py` to reraise the exception? I.e. add `raise` in a new line after line 23.

**Comment by teto** [comment]
I added a except "Exception as e: print(e) " l.33/35 and the error was
"Type str does not support the buffer API" so I guess the error rather
happens on the line "revision = pipe...."
So I guess the warning about a git error is misleading and khal should
print the real error.

I run python 3.4.2 on Ubuntu.

Note: It doesn't prevent installing khal, it's just a warning.
Note2: I installed khal on another computer with ubuntu without any problem


2015-06-04 14:04 GMT+02:00 Markus Unterwaditzer <notifications@github.com>:

**Comment by hobarrera** [comment]
python3-only issue, apparently, and only when installing from git from what I see.

**Comment by untitaker** [comment]
I currently can't push to github for some reason but I'm currently working on it.

**Comment by untitaker** [comment]
Fixed. I don't think tests are that necessary, see #182.

**Comment by teto** [comment]
I confirm it makes the error disappear, I don't think it's necessary to test a warning.

**Comment by hobarrera** [comment]
Keep in mind that it's not just a warning: the built package will defer too (it will lack the exact git version data).

However, if we move to setuptools_scm, those tests would become useless.
