### ISSUE TITLE
How to add emacs bindings?

### ISSUE THREAD

**Issue by edt-devel** [geier/khal#213]
How can I add emacs bindings like C-n for right?

**Comment by geier** [comment]
you should be able to add the via the config file, e.g.:

    [keybindings]
    right = right, ctrl n

**Comment by edt-devel** [comment]
Thank you!
I only tried C-n and the like and missed the obvious...

**Comment by geier** [comment]
I guess I need to update the documentation on how to make keybindings with modifiers work.
