### ISSUE TITLE
Strange time formatting

### ISSUE THREAD

**Issue by nielsk** [geier/khal#216]
Any idea why khal displays times in my case like this:
```
10 =30-11 =30: Event Name
```
?

**Comment by hobarrera** [comment]
Can you post your khal.conf, please?

**Comment by nielsk** [comment]
Closed…Pebcak-problem
I had to change my khal.conf and did it with a mass-replacement and with that ":" got changed to " =", thus the strange formatting. m) 
Sorry for the inconvenience
