### ISSUE TITLE
It is not possible to delete a single instance from a recurring event

### ISSUE THREAD

**Issue by nielsk** [geier/khal#217]
Let's say I have a daily recurring event and I want to delete one instance of this event (in ikhal), then all events of the recurring event get deleted and not only the one instance.
There should be either a dialogue if all events or only this one event should be deleted or imho better:
d - delete only the selected instance
D - delete all instances of the recurring event

**Comment by geier** [comment]
I'm working on this. There is already some UI code in branch
`deleteRecurring` (for your first suggestions), but the current Event
object had no support for this.  This is actually the main reason I'm
currently reworking Event and a lot of the "backend" (yes, again).

I like the second idea, too, but this will be doable very quickly one
the rest has been setup.

Quoting Niels Kobschätzki (2015-07-04 16:10:57)
