### ISSUE TITLE
Install instructions on webpage incomplete

### ISSUE THREAD

**Issue by stweller** [geier/khal#227]
I realize this is just a detail, but in the install instructions on the webpage it should say that if you install via pip without lxml, you need to have not only python and libxml2 headers, but also xslt1 headers (at least I had to install libxslt1-dev for the installation to succeed on Debian 7.8.

Thanks for your work!

**Comment by hobarrera** [comment]
This seems to be correct, as par the [lxml website](http://lxml.de/installation.html). I'll fix this ASAP.
