### ISSUE TITLE
[0.6.0] ImportError

### ISSUE THREAD

**Issue by matthiasbeyer** [geier/khal#230]
When starting khal version 0.6.0, I get an import error instantly:

```
$ khal
[...]
    from khal.version import version
ImportError: No module named version
```

**Comment by geier** [comment]
the version file should be auto-generated during setup or while creating the package. How did you get and install khal?

**Comment by untitaker** [comment]
@geier I don't see how since we use setuptools-scm now.

**Comment by geier** [comment]
this line *should* do the trick https://github.com/geier/khal/commit/886a3545307d6058b410f342e314364e4272518a#diff-2eeaed663bd0d25b7e608891384b7298R45

**Comment by untitaker** [comment]
I see, it works for me too. @matthiasbeyer could you give us the full output of `setup.py install`?

**Comment by benjaminfrank** [comment]
Just guessing here, I think the issue manifests itself if someone uses the release tarballs and not git as tin this case setuptools_scm does not find any scm info to build version.py

**Comment by geier** [comment]
did you get the release tarballs from github? the *official* ones from [pypi](https://pypi.python.org/pypi/khal) or [khal's website](https://lostpackets.de/khal/news/khal06.html) should have a `version.py` file included.

**Comment by untitaker** [comment]
cc @0-wiz-0 I think this is relevant to vdirsyncer.

**Comment by matthiasbeyer** [comment]
I'm installing through my Packagemanager, which installs khal [from this derivation](https://github.com/NixOS/nixpkgs/blob/master/pkgs/applications/misc/khal/default.nix) which I updated to khal 0.6.0. I'm the package maintainer of the pkg, I tried to update and ran into the error reported here.

**Comment by plega** [comment]
I  used the zipfile  from the "download now" button (I know, I know) and there was no version.py file.   Same problem as the above.

**Comment by plega** [comment]
The svn copy [r1021] is also missing version.py for tags/v0.6.0.

**Comment by geier** [comment]
The SCM should never contain the version.py file, it gets generated when calling setup.py and gets included in the distribution archives. It does need the `.git` directory to to find the last tag. If it turns out this breaks the workflow of too many users, I'll revert to the old way of generating a version.py.

As a quick and dirty fix you can just create a file `khal/version.py`  with the line `version = 1.2.3`.

And it looks like setuptools_scm does not support svn (yet?).

**Comment by plega** [comment]
I've switched to using git clone... but you might want to add a README
if a svn fix is going to wait for an indefinite length of time.

Philip

On Tue, Jul 21, 2015 at 10:50:51AM +0100, Christian Geier wrote:
> The SCM should never contain the version.py file, it gets generated when calling setup.py and gets included in the distribution archives. It does need the `.git` directory to to find the last tag. If it turns out this breaks the workflow of too many users, I'll revert to the old way of generating a version.py.
> 
> As a quick and dirty fix you can just create a file `khal/version.py`  with the line `version = 1.2.3`.
> 
> And it looks like setuptools_scm does not support svn (yet?).
> 
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/geier/khal/issues/230#issuecomment-123244720

-- 
Philip Allen, Executive Chairman, CoreFiling Limited
http://www.corefiling.com
Phone: +44-1865-203192  Mobile: +44-7956-160959

**Comment by untitaker** [comment]
I've just introduced a check in `vdirsyncer/__init__.py` to deal with this, @geier you might want to copy it.

**Comment by RonnyPfannschmidt** [comment]
on a sidenote, unlike mercurial tarballs (which are supported by setuptools_scm) unpacked git tarballs completely lack metadata, (except for guessign from the folder name if one is lucky)

since git is so bad at that, i opted for not supporting git tarballs

**Comment by geier** [comment]
@plega yes, I'll put something in the README, and make it print a warning if a svn or github tarball is used (like @untitaker suggested).

@RonnyPfannschmidt now that you mention it I remember you ranting about how bad git is in that regard

**Comment by RonnyPfannschmidt** [comment]
@geier the next version of setuptools_scm will properly error out with such occasions (devpi-client did also cause some issues),
the release will happen this week, afterwards you could just pin the version

**Comment by geier** [comment]
@RonnyPfannschmidt awesome, thanks!

**Comment by geier** [comment]
@matthiasbeyer please change the link in the package to  https://pypi.python.org/packages/source/k/khal/khal-${version}.tar.gz

**Comment by matthiasbeyer** [comment]
I'm trying this, hang on.

**Comment by matthiasbeyer** [comment]
Seems to work, thanks a lot.

**Comment by geier** [comment]
Thanks for bringing this to our attention (and for taking care of a package!)

**Comment by matthiasbeyer** [comment]
You're welcome!
