### ISSUE TITLE
"at" doesn't show events for the day

### ISSUE THREAD

**Issue by teto** [geier/khal#238]
I am using current master 151a8395a1812c42be4159aa39b5cdc2ed0036b0 and when I do 
"ikhal at 07.09." for instance, it doesn't show any events while I have events shceduled for that day. I can see them with ikhal.
I don't know if it worked before since this is my first time using the "at" command.

**Comment by geier** [comment]
try `khal agenda 07.09.`, `at` should only work with datetimes (so there is a bug here).

**Comment by teto** [comment]
I've upgraded to latester master. Using khal agenda indeed works while at keeps displaying nothing.
Thanks
