### ISSUE TITLE
CET date displays wrong in khal:Europe/London

### ISSUE THREAD

**Issue by plega** [geier/khal#239]
khal continues to impress me, and I now use it synced to both SOGo and davical.

But.. perhaps I'm being a muppet, but I have tried importing a Microsoft ICS file into SOGo and it displays correctly, but when I look at it through khal it comes out wrong.

ICS file: 11-12.00 CET 5 Sept  - Desired output
SOGo display: 10-11.00 BST [Europe/London daylight saving] - Desired output
khal display: 9-10.00 Europe/London [local and default] - Wrong output

Have I done something wrong or it this a khal problem?  (Sorry if it's the former.)

File:
BEGIN:VCALENDAR
PRODID:-//Microsoft Corporation//Outlook 12.0 MIMEDIR//EN
VERSION:2.0
METHOD:REQUEST
X-MS-OLK-FORCEINSPECTOROPEN:TRUE
BEGIN:VEVENT
ATTENDEE;CN='plega@tmp.com';RSVP=TRUE:mailto:plega@tmp.com
	ail.com
CLASS:PUBLIC
CREATED:20150727T160348Z
DESCRIPTION:[test] Quand : vendredi 4 septembre 2015 11:00-12:00 (UTC+01:00) Bruxe
	lles\, Copenhague\, Madrid\, Paris.\nEmplacement : 
DTEND:20150905T100000Z
DTSTAMP:20150727T160348Z
DTSTART:20150905T090000Z
LAST-MODIFIED:20150727T160348Z
LOCATION:Conf call +33(0)1234568
ORGANIZER;CN="foo@bar.com
PRIORITY:1
SEQUENCE:6
SUMMARY;LANGUAGE=fr:Next call - 4th of September 11:00-12:00 CET. 
TRANSP:OPAQUE
UID:0400A0C4A4A795C8D0010012345680000000000000
X-MICROSOFT-CDO-BUSYSTATUS:TENTATIVE
X-MICROSOFT-CDO-IMPORTANCE:2
X-MICROSOFT-CDO-INTENDEDSTATUS:BUSY
X-MICROSOFT-DISALLOW-COUNTER:FALSE
X-MS-OLK-ALLOWEXTERNCHECK:TRUE
X-MS-OLK-APPTLASTSEQUENCE:6
X-MS-OLK-APPTSEQTIME:20150721T152532Z
X-MS-OLK-AUTOSTARTCHECK:FALSE
X-MS-OLK-CONFTYPE:0
X-MS-OLK-SENDER;CN=mailto:foo@bar.com
END:VEVENT
END:VCALENDAR

**Comment by plega** [comment]
This appears to be an import issue.

I viewed the event in SOGo and saved it again, and then ran vdirsyncer again.  This time it displayed correctly in khal.  The relevant lines of the diff between the original file (which I imported by dropping it into the vdirsyncer local directory) and the one synced back from SOGo are:

< METHOD:REQUEST
< X-MS-OLK-FORCEINSPECTOROPEN:TRUE
---
> BEGIN:VTIMEZONE
> TZID:Europe/London
> X-LIC-LOCATION:Europe/London
> BEGIN:DAYLIGHT
> TZOFFSETFROM:+0000
> TZOFFSETTO:+0100
> TZNAME:BST
> DTSTART:19700329T010000
> RRULE:FREQ=YEARLY;BYMONTH=3;BYDAY=-1SU
> END:DAYLIGHT
> BEGIN:STANDARD
> TZOFFSETFROM:+0100
> TZOFFSETTO:+0000
> TZNAME:GMT
> DTSTART:19701025T020000
> RRULE:FREQ=YEARLY;BYMONTH=10;BYDAY=-1SU
> END:STANDARD
> END:VTIMEZONE

< DTSTART:20150905T090000Z
< LAST-MODIFIED:20150727T160348Z
---
> DTSTART;TZID=Europe/London:2015090tT100000
> LAST-MODIFIED:20150729T062046Z

I guess I'm using the wrong technique for importing into khal ?

**Comment by geier** [comment]
If you are using vdirsyncer you are doing everything right. I'll have a look ASAP.

**Comment by geier** [comment]
Could you recheck this? I believe I fixed this together with #240 (as DTSTART values in Zulu time were erroneous interpreted as floating time events).

**Comment by plega** [comment]
#240 is fixed, but this one is not, I'm afraid.  I still get the same result as above.

**Comment by plega** [comment]
Using the same file as above (9-10 a.m. Zulu Time), I import it into Sogo, vdirsync it, and then:

1. view in ikhal (Europe/London) - shows 9-10 a.m. [WRONG]
2. search in khal - shows 10-11 a.m. [CORRECT]

**Comment by geier** [comment]
I believe I fixed this (you may need to delete your database), please reopen if I didn't.

**Comment by plega** [comment]
I confirm that this is fixed - I have run it successfully in 0.6.1.dev76+ng5fc2d14
