### ISSUE TITLE
Add which birthday it is

### ISSUE THREAD

**Issue by mathstuf** [geier/khal#242]
With birthday events, it would be nice to be able to have the description say that it's the "34th" birthday.

**Comment by libre-man** [comment]
I wrote something that works for agenda and calendar but not for ical. The best way would be to generate the summary dynamically based on if the event is a birthday but the event class should be changed and that is a lot more work.

**Comment by geier** [comment]
@libre-man you could just add a new event class, I don't think this would be too much work. If you want to work on this and need any help, please do contact me.
