### ISSUE TITLE
Trouble adding events

### ISSUE THREAD

**Issue by jetpacktuxedo** [geier/khal#252]
I throw an assertion error at line 241 in aux.py

If I remove this line I can create events without issue.

The assertion seems to have been added recently (commit 8832c4e13fd4e02fba128a9087f5c16e0fcdff41).

**Comment by geier** [comment]
can you please paste the output (run khal with `-v` please) and how you invoke khal?

@untitaker what does this assertion defend against?

**Comment by jetpacktuxedo** [comment]
Sure thing. I dumped it into this gist: https://gist.github.com/jetpacktuxedo/5107bd0a5f4e2fad4659

When I comment out the assertion everything seems to work as expected. It doesn't throw any errors and the event appears in the calendar.

**Comment by geier** [comment]
What does it actually add to the database (when the assertion is removed)?

Correctly, you should call khal with `khal -v new -a home 1:00 beer` and you should actually see an error, but probably more like `Cannot parse: 'beer 01:00'`

**Comment by jetpacktuxedo** [comment]
Actually yeah, you're right. I hadn't run it with -v before, but I get 
    critical: Cannot parse: 'beer 1:00'
    critical: Please have a look at the documentation.

From what I can tell, I match the syntax in the docs. Am I doing something wrong, or is 

Shit, disregard all of that, I just realized that that isn't how I was running it to get the assert.

The correct version of that syntax is `khal -v new -a home 1:00 beer`

Rerunning it with the right syntax both with and without the assert. With the assert, I get the output shown here: https://gist.github.com/jetpacktuxedo/8c703519255674c2b758

Without the assert, the debug info looks very similar (if not the same) except it doesn't end it a traceback

**Comment by geier** [comment]
I removed the assert for now, I believe there was a mixup of some sort. 

Thanks foot reporting! 

Am 25. August 2015 00:57:12 MESZ, schrieb Ethan Madden <notifications@github.com>:

**Comment by untitaker** [comment]
Sorry about that assertion, I think I was confused. However, that type really should be consistent.

On 22 August 2015 02:04:18 CEST, Ethan Madden <notifications@github.com> wrote:
>I throw an assertion error at line 241 in aux.py
>
>If I remove this line I can create events without issue.
>
>The assertion seems to have been added recently (commit
>8832c4e13fd4e02fba128a9087f5c16e0fcdff41). 
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/geier/khal/issues/252

-- 
Sent from my phone. Please excuse my brevity.

**Comment by geier** [comment]
Did you perhaps mean `compat.unicode_type`?

**Comment by untitaker** [comment]
I tried all types, but I think there's some inconsistency on some inputs.

On 25 August 2015 13:10:28 CEST, Christian Geier <notifications@github.com> wrote:
>Did you perhaps mean `compat.unicode_type`?
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/geier/khal/issues/252#issuecomment-134556226

-- 
Sent from my phone. Please excuse my brevity.
