### ISSUE TITLE
khal new does not work

### ISSUE THREAD

**Issue by matthiasbeyer** [geier/khal#262]
All I know:
```
$ khal new -a studying -l someroomnumber -r weekly --until 31.01.2016 SomeEvent
critical: Cannot parse: 'SomeEvent'
critical: Please have a look at the documentation.
```

**Comment by untitaker** [comment]
I think you still have to include a start and end date as usual.

**Comment by untitaker** [comment]
Eg this works (different dateformat in my config tho):

    khal new -a default -l someroomnumber -r weekly --until 2016-09-09 2013-09-09 SomeEvent

**Comment by matthiasbeyer** [comment]
The help text `khal new --help` does not state that I need a start date!

**Comment by untitaker** [comment]
That's... yeah. It's not pretty.

**Comment by geier** [comment]
@untitaker is it possible to override click's usage string?

**Comment by untitaker** [comment]
@geier Completely override it, or just that part?

I'd rather recommend writing in the docstring how DESCRIPTION (bad name?) should look like, but you can subclass `Command` and override any of the `format_*` methods.

**Comment by geier** [comment]
Quoting Markus Unterwaditzer (2015-09-22 23:09:56)
> @geier Completely override it, or just that part?
only that part, but your suggestion is probably a good one (and
*description* does  kind of suck....)

**Comment by geier** [comment]
I believe 2d9a68cc8b411cf6d6b29853 should fix this, if you have better ideas, please don't hesitate to reopen this or a new issue/pull request.

**Comment by untitaker** [comment]
It seems hacky to generate the event list and later parse it again.

**Comment by geier** [comment]
I couldn't agree more. But I think the user facing documentation is much clearer now and I  without delving too much into click's internal I had no idea how else to do it. If you know a cleaner solution I'd love too see it.

**Comment by untitaker** [comment]
The click parts are fine, but after retrieving the data from click, assembling and disassembling the list is hacky. I'll make a PR.

**Comment by untitaker** [comment]
Would it be fine to make start, end etc options?

**Comment by geier** [comment]
I'd hate to see the current usage pattern go. `khal new 5.8. 13:00 15:00 Meeting` is so much quicker and more convenient to type than `khal new --start 5.8. 13:00 --end 15:00 --summary Meeting` (`-s` and `-e` wouldn't make it better in my eyes).

**Comment by untitaker** [comment]
But one of them is easier to remember.

You can always build dirty shortcut interfaces over sane verbose ones, but
doing the opposite is worse.

**Comment by geier** [comment]
In this case, I don't think one can build a dirty interface over the clean one (without replicating all of it's current behaviour). But I'm not against having different implementations internally, adding e.g. a natural language processing one would need another one anyway.
