### ISSUE TITLE
Feature request: Don't print colors but ANSI color and style sequences

### ISSUE THREAD

**Issue by matthiasbeyer** [geier/khal#263]
Use case:

```
watch -n 600 khal agenda --days=20 --ansi-color
```

Would be really nice.

**Comment by geier** [comment]
I'm not really sure what you want mean here.  Could you provide an example output?

**Comment by matthiasbeyer** [comment]
No, I cannot because I cannot put colored output here on github.

The thing is: `watch` can interpret ansi escape codes, so if you pipe in anis-escape codes it will print them as colors. If `khal agenda` would print these escape codes, watch would produce colored output.

**Comment by untitaker** [comment]
I think you want khal to output colors no matter whether stdout is a TTY.

**Comment by untitaker** [comment]
Try this:

    watch -n 600 'script -qc "khal agenda --days=20"'

My `watch` doesn't seem to interpret escape codes though, and somehow mangles them.

**Comment by matthiasbeyer** [comment]
Nope, I get the escape sequences as plain text.

If I enable escape sequence encoding in `watch` (with `-c`) it segfaults. I guess this is an issue with `watch`, not with `khal`.

**Comment by untitaker** [comment]
Hmm, it works perfectly fine for me, version is `watch from procps-ng 3.3.11`.

Actually providing an option to do this in khal would require upstream patches, or monkeypatching of the Python runtime. Also I think `script` works fine for this purpose.

Can this be closed?

**Comment by matthiasbeyer** [comment]
Yes, this can be closed. Thanks for supporting me with this.
