### ISSUE TITLE
ikhal: No events shown on today 

### ISSUE THREAD

**Issue by ejeandel** [geier/khal#265]
Hi

When I launch ikhal, it does not show me any events for today.
If I change date, e.g. by going left then right, then the events for today start to appear.

I don't know when this regression appeared, I assume this is a problem with the on_date_change routine, but I might be wrong.

**Comment by lkraav** [comment]
Confirming same experience here.

**Comment by geier** [comment]
Thanks for reporting, I'll have a look tonight.

**Comment by geier** [comment]
I believe I fixed this, could you give it a try?

**Comment by lkraav** [comment]
`ikhal, version 0.6.1.dev96+ngd7bcf32` seems to behave correctly now

**Comment by geier** [comment]
Thanks for reporting and checking again.

**Comment by ejeandel** [comment]
I confirm it is fixed, thanks.
