### ISSUE TITLE
query: pkginfo dependency

### ISSUE THREAD

**Issue by okapia** [geier/khal#279]
khal.egg-info/requires.txt lists pkginfo as a dependency but I can't find where this dependency is being used. I can't find any other reference to it and can't think what it'd be needed for. Is it definitely needed? At least as far as my testing goes, khal is working fine without it.

I'm in the process of packaging khal for Void linux and would prefer not to have to package any more dependencies than necessary. Thanks

**Comment by geier** [comment]
I don't think it is needed anymore, looks like I forgot to remove it. Thank you for taking the time to make a package!

**Comment by geier** [comment]
I've just removed it from the requirements list.
