### ISSUE TITLE
Make it possible to see location and description with agenda

### ISSUE THREAD

**Issue by libre-man** [geier/khal#282]
I would really like to be able to see the location and description when using `khal agenda`. This could be made possible by a full flag or something alike.

**Comment by libre-man** [comment]
I have this function working in a fork, but I don't know if a full flag is the best option. Maybe a distinct flag for description and location.

**Comment by geier** [comment]
Thanks for your pull request,  I believe --full is the better option for now.

In the future I would like to make the printing of events fully customizable, perhaps with a short/normal and a long/full mode.

**Comment by geier** [comment]
closed with #283
