### ISSUE TITLE
Saving recurring events: Nullpointer in RecursionEditor

### ISSUE THREAD

**Issue by JKatzwinkel** [geier/khal#284]
This happens in `khal interactive` mode.
Whenever I try to save an event (no matter if a new or an existing one) the frequency of which I changed from the default 'No' to whatever, `khal` crashes due to the following error:

      File "/usr/lib/python2.7/site-packages/khal/ui/__init__.py", line 543, in save
        self.update_vevent()
      File "/usr/lib/python2.7/site-packages/khal/ui/__init__.py", line 514, in update_vevent
        rrule = self.recursioneditor.active
      File "/usr/lib/python2.7/site-packages/khal/ui/__init__.py", line 306, in active
        self.rrule["freq"] = [recursive]
    TypeError: 'NoneType' object does not support item assignment

This regards `khal 0.6.0`, built and installed via AUR (`0.6.0-1`).

**Comment by geier** [comment]
Thank you for reporting this bug. Though it looks like this is fixed in master, I'll leave this open until the next release.

**Comment by JKatzwinkel** [comment]
It looks like fixed indeed. After reinstall as `khal-git` (`v0.6.1.dev166`) via AUR, editing recurring events behaves as it should. Thank you for pointing that out.

**Comment by hobarrera** [comment]
0.7.0 includes fix.
