### ISSUE TITLE
Week numbers in khal and ikhal

### ISSUE THREAD

**Issue by dzoep** [geier/khal#288]
I would like to add an option to khal/ikhal, that would enable display of week numbers in calendar views (as in strftime's %U, %V or %W).

If nobody is working on this I'd gladly implement it.

It is actually part of bigger thing on my wish-list - for weekly events, be able to specify repeated events for odd and even weeks separately.

**Comment by geier** [comment]
Khal and ikhal can already display week numbers, have a look at the configuration documentation. Better specification of recurring events is needed though (IMHO especially in ikhal).

**Comment by dzoep** [comment]
Mea culpa. This is exactly what I need. So maybe I'll move on to the next part - support for INTERVAL>1 with given FREQ values (weekly, monthly is definitely needed, don't know if other variants would be more appropriate for daily freq). May I rename this issue?

**Comment by geier** [comment]
@dzoep please rename if you want to (probably makes sense, or even close and start a new one, I don't mind)
