### ISSUE TITLE
X-APPLE... tag causes ikhal to not display entry

### ISSUE THREAD

**Issue by plega** [geier/khal#294]
Adding the following text to an ical file causes the entry not to appear in ikhal:

X-APPLE-STRUCTURED-LOCATION;X-TITLE=64 Buckingham Palace Rd\, London EC4 3N
 A;X-APPLE-RADIUS=49.91307046514149;VALUE=URI;X-APPLE-MAPKIT-HANDLE=CAESvgI
 aEgm8EGGyp8BJQBG/3rNkRFjJvyLeAQoOVW5pdGVkIEtpbmdkb20SAkdCGgdFbmdsYW5kKgZMb
 25kb24yBkxvbmRvbjoGVzggN05BQiFCb3JvdWdoIG9mIEtlbnNpbmd0b24gYW5kIENoZWxzZWF
 SEVNoZWZmaWVsZCBUZXJyYWNlWgI2NGIUNjQgU2hlZmZpZWxkIFRlcnJhY2VyDUdyZWF0IEJya
 XRhaW6KAQpLZW5zaW5ndG9uigEWS2Vuc2luZ3RvbiBhbmQgQ2hlbHNlYYoBIUJvcm91Z2ggb2Y
 gS2Vuc2luZ3RvbiBhbmQgQ2hlbHNlYSoUNjQgU2hlZmZpZWxkIFRlcnJhY2UyFDY0IFNoZWZma
 WVsZCBUZXJyYWNlMgZMb25kb24yBlc4IDdOQTIHRW5nbGFuZDg5QAA=;X-APPLE-REFERENCEF
 RAME=1:geo:51.505118,-0.198006

**Comment by geier** [comment]
Which version of khal are you on and are there any error messages?

**Comment by plega** [comment]
v0.6.1.dev76+ng5fc2d14

No error messages at all.


On Tue, Nov 03, 2015 at 09:53:01PM +0000, Christian Geier wrote:
> Which version of khal are you on and are there any error messages?
> 
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/geier/khal/issues/294#issuecomment-153501014

-- 
Philip Allen, Executive Chairman, CoreFiling Limited
http://www.corefiling.com
Phone: +44-1865-203192  Mobile: +44-7956-160959

**Comment by geier** [comment]
I just looked at this line more carefully: this line is not actually valid.

Obviously, just failing without any warning at all is not a good idea.

With what program did you create the file?

**Comment by geier** [comment]
also the collective/icalendar#168

**Comment by plega** [comment]
Created by a colleague on a very new iphone - probably an i6 - but I
don't know the details.

Regards

Philip

On Wed, Nov 18, 2015 at 11:07:11PM +0000, Christian Geier wrote:
> I just looked at this line more carefully: this line is not actually valid.
> 
> Obviously, just failing without any warning at all is not a good idea.
> 
> With what program did you create the file?
> 
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/geier/khal/issues/294#issuecomment-157893887

-- 
Philip Allen, Executive Chairman, CoreFiling Limited
http://www.corefiling.com
Phone: +44-1865-203192  Mobile: +44-7956-160959
