### ISSUE TITLE
ikhal: better help

### ISSUE THREAD

**Issue by geier** [geier/khal#30]
these commands seem to be unmentioned:
    - 'n'   create a new event.
    - 'd'   delete event.
    - 'TAB' Swicth focus.
    - Left arrow to go back to calendar.

**Comment by untitaker** [comment]
Do we have to describe that "left" goes back into the calendar walker? I think this is implied by "arrows: navigate through calendar"

**Comment by geier** [comment]
I thought about generating the help text from the keybindings, so it shows accurate information.

**Comment by untitaker** [comment]
Not sure, some keybindings are implictly given by urwid's widget types.

**Comment by geier** [comment]
at least the arrows are overridden now

**Comment by geier** [comment]
at least in the calendar

**Comment by geier** [comment]
I believe this was fixed by untitaker.
