### ISSUE TITLE
Highlighting introduced in d00281133e674468e5a7d032161409c9430efa90 is incompatible with solarized theme

### ISSUE THREAD

**Issue by ralphholz** [geier/khal#303]
Hi,

I've just found out that the highlighting from d00281133e674468e5a7d032161409c9430efa90 produces artefacts in a gnome-terminal (identifying itself as xterm-256color) that's running a solarized theme (http://ethanschoonover.com/solarized). Names of days of the week and months become unreadable (all-white background, extremely faint highlighted foreground).

I thought you might want to know about that. d00281133e674468e5a7d032161409c9430efa90 was discussed and merged in #276.

I am not sure yet if the problem has to do with code or with the solarized theme.

**Comment by hobarrera** [comment]
Colors are configurable, so that might do half the job of fixing it. Have you tried that?

I do think something we're missing the ability to configure both bg *and* fg for highlighting. Or merely just **bold**ing highlighted text.

**Comment by geier** [comment]
Thank you for reporting this, I believe I just fixed this issue. Could you have a look if it works for you as well?

**Comment by ralphholz** [comment]
I am on 79a84292d32cef0fd00344a7aa1b40251cf2a4e9 now and I can confirm that the issue has gone. Thanks for fast response!

**Comment by geier** [comment]
Thank you for reporting it!
