### ISSUE TITLE
travis ci: style tests run py.tests as well

### ISSUE THREAD

**Issue by geier** [geier/khal#317]
since the introduction of the NEGTZ variant, the style tests that should only run flake8 also run py.test (e.g. [945.2](https://travis-ci.org/geier/khal/jobs/98964527)). @hobarrera @untitaker If one of you knows their way around travis, could you have a look?

**Comment by untitaker** [comment]
style + negtz are ran in `.travis.run.sh`. I'd say we remove the negtz environment and use pytest's monkeypatching if possible.

**Comment by untitaker** [comment]
nvm about the monkeypatching, but I think we can do without the extra env
