### ISSUE TITLE
reformating agenda layout

### ISSUE THREAD

**Issue by Cutuchiqueno** [geier/khal#325]
The agenda layout looks very messy and is difficult to read. Wouln't it be helpful to put a blank line between each day, meaning the last entry of the last day and the date of the next day like this:

    Today:
    #1Lib1Ref Day at Wikipedia
    BitCurator Users' Forum
    18:00-22:00: Telota Weihnachtsbowlen

    Tomorrow:
    10:00-11:00: Frühstück mit Sophie

it could be optional, but I would very much like to see the agenda a bit more structured

Thanks for your attention

**Comment by geier** [comment]
Thank you for your comment, while I'll close this as a duplicate of #267, perhaps you have some ideas how agenda (and calendar) should work in general, what arguments and options are needed, etc. If so, please comment in #273.
