### ISSUE TITLE
Multiple events ICS file

### ISSUE THREAD

**Issue by cedricpim** [geier/khal#329]
First of all, great work on khal.

I come up with an issue where I am trying to make khal read from a directory with multiple `.ics` files and each of these files has lots of events. In this situation, the name of each event is displayed with the last event of the file, but if I separate each event to a separate `.ics` file, everything works properly. Any idea why this happens?

Thanks.

**Comment by hobarrera** [comment]
Quoting @untitaker here on a similar issue for todoman:

> Multiple events components in one file is a format that vdirsyncer can't support. In order to preserve interopability with other vdir implementations (such as vdirsyncer) [...]

There is a vdirsyncer backend that you can use to read from a single large file and spit that into individual files. That might help.

**Comment by cedricpim** [comment]
Thank you. Can you elaborate on which vdirsyncer backend you are talking about?

**Comment by untitaker** [comment]
He means "singlefile". Do you need to have this format for import or storage?

On 30 January 2016 18:02:51 CET, Cedric Pimenta <notifications@github.com> wrote:
>Thank you. Can you elaborate on which vdirsyncer backend you are
>talking about?
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/geier/khal/issues/329#issuecomment-177246059

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by hobarrera** [comment]
https://vdirsyncer.readthedocs.org/en/stable/config.html#storage-singlefile

**Comment by cedricpim** [comment]
Right now, I created a script to go through my google calendars and build an `.ics` file with the events. 
Now the only part missing is being able to that these `.ics` files and display them on khal. Maybe import is the way to go.

**Comment by hobarrera** [comment]
> Right now, I created a script to go through my google calendars and build an .ics file with the events. 

Doesn't google expose their events as CalDav anymore? Can't you use `vdirsyncer`for that?

**Comment by cedricpim** [comment]
Now they have the whole OAuth authentication process so `vdirsyncer` no longer works for that sadly.
Thanks for the help, I think we can close :+1:

**Comment by untitaker** [comment]
IIRC you can actually do read-only access without OAuth, see https://vdirsyncer.readthedocs.org/en/stable/supported.html#google

I certainly wouldn't rely on it. Your solution probably is more robust against Google's plans.
