### ISSUE TITLE
feature request: identify 24:00 with 00:00 the next day.

### ISSUE THREAD

**Issue by lucc** [geier/khal#336]
I was running `khal new tomorrow 20:00 24:00 foo` and was hoping to get an event that lasted till the end of tomorrow (it would have worked if I used `khal new tomorrow 20:00 00:00 foo` instead as the end time is moved to the future until it is after the start time automatically). Instead the event lasts for one hour and the summary is "24:00 foo".

Do you think it is a reasonable feature to identify the string "24:00" as "00:00" of the next day in places that would accept a time string?

**Comment by geier** [comment]
Good idea, this is probably what users expect. What would be the equivalent of 24:00 in an am/pm notation?

**Comment by lucc** [comment]
[wikipedia](https://en.wikipedia.org/wiki/12-hour_clock#Confusion_at_noon_and_midnight) says that it is complicated to decide :) We can follow the main wiki article and take 12am for midnight.

That's one more reason why I like a 24h clock.

**Comment by hobarrera** [comment]
Technically, 00:01 is 12:01am (due to being before midday or *ante meridiem*).  
Then again, 12:01 is 12:01pm (being one minute **after** midday).  

It's hard to say where the am/pm equivalent for 24:00 would fall. Following the logic above, it should be pm (it's after midday), but that would conflict with midday.

**Comment by lucc** [comment]
Tank you :)

**Comment by geier** [comment]
We probably need some documentation on this (and perhaps check if the locale is set to 24 hour format).

**Comment by geier** [comment]
and btw: thanks @lucc for the good suggestion.

**Comment by geier** [comment]
fixed
