### ISSUE TITLE
feature request: 'clean' output for use in conky

### ISSUE THREAD

**Issue by AcouBass** [geier/khal#338]
Hi,

I've been running khal in conky with the following line:  
`${execpi 36000 khal}`  

Which while it works, gives a lot of garbage on the display. I'd be interested to see a CLI flag for khal that would give a conky-compatable output. Picture attached is how it looks right now (Top) with how it would ideally look (Bottom) - I did this by simply piping the khal output to a text file and manually deleting the extras for the bold/colourful characters.  

Apparently this is an issue gcalcli has too (Which I discovered when searching for a fix) and seems to be a limitation with Conky not supporting the special characters used.
![20160214- 013131](https://cloud.githubusercontent.com/assets/10049104/13031172/b5acd756-d2ba-11e5-9f15-6f30d21e14d4.png)

**Comment by hobarrera** [comment]
It looks like colour codes are getting in the way for you. As a temporary workaround, running this might help:

    khal | sed -r "s/\x1B\[([0-9]{1,2}(;[0-9]{1,2})?)?[mGK]//g"

I do agree that a `--no-color` flag *may* be useful if there's sufficient demand for it.

**Comment by geier** [comment]
We could also do this automatically if stdout is not a tty (`sys.stdout.isatty()`). Suggestions?

**Comment by hobarrera** [comment]
> We could also do this automatically if stdout is not a tty (sys.stdout.isatty()). Suggestions?

I've never really like that behaviour, because, aside from not being very unixy, it breaks colours when you run `khal | less`, `ssh somehost khal`, and things like that.

**Comment by untitaker** [comment]
I have no idea what "unixy" means but this is standard behavior for most reasonable tools that output color. Including `grep` and `git`.

**Comment by untitaker** [comment]
I've opened #361. It should just work without extra options. If it doesn't, use `khal calendar | cat`, or ask the conky devs.

**Comment by louwers** [comment]
Did anything write a parser of khal's output to include coloring for Conky?

**Comment by untitaker** [comment]
Not that I know of. What would be more generally useful is a script that converts ANSI colorcodes to conky color commands.

**Comment by rsteube** [comment]
This works for me:
```
#!/bin/sed -f
s/\^[\[[0-9]\?\([0-9]\+\);\?[^m]*m/${color\1}/g
```
see https://github.com/rsteube/ansi2conky
