### ISSUE TITLE
TypeError trying to start ikhal

### ISSUE THREAD

**Issue by minego** [geier/khal#350]
% ikhal
Traceback (most recent call last):
  File "/usr/bin/ikhal", line 9, in <module>
    load_entry_point('khal==0.7.1.dev109+ng3fb3973.d20160208', 'console_scripts', 'ikhal')()
  File "/usr/lib/python3.5/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3.5/site-packages/click/core.py", line 675, in main
    _verify_python3_env()
  File "/usr/lib/python3.5/site-packages/click/_unicodefun.py", line 69, in _verify_python3_env
    if locale.lower().endswith(('.utf-8', '.utf8')):
TypeError: a bytes-like object is required, not 'str'

**Comment by geier** [comment]
Thank you for reporting this, but I believe this is a bug in click, see https://github.com/mitsuhiko/click/issues/490.

**Comment by untitaker** [comment]
Please try updating click.

**Comment by minego** [comment]
Sorry, Python isn't a language I'm all that familiar with. Thanks for the
help.

**Comment by untitaker** [comment]
How did you install khal?

**Comment by minego** [comment]
Using the AUR from arch Linux.

https://aur.archlinux.org/packages/khal-git/

**Comment by untitaker** [comment]
Ok, the `[community]` repo should soon-ish have python-click 6.3 and this bug will fix itself.

**Comment by minego** [comment]
Perfect. Thank you.

**Comment by minego** [comment]
Closing based on comments that this is a bug in mitsuhiko/click

**Comment by untitaker** [comment]
Ok, please reopen if the bug persists with click  6.3

On 23 February 2016 17:29:59 CET, Micah N Gorrell <notifications@github.com> wrote:
>Closing based on comments that this is a bug in mitsuhiko/click
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/geier/khal/issues/350#issuecomment-187774627

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by minego** [comment]
Will do, thanks again.
