### ISSUE TITLE
Drop support for per-calendar color setting

### ISSUE THREAD

**Issue by hobarrera** [geier/khal#370]
We currently have two ways of configuring a calendar's colour: the configuration file, and the `color` file inside the vdir.

I'd much rather just keep one (for simplicity's sake). Since the latter is part of a vdir, and also synched by vdirsyncer (as well as readable by other clients), I believe it's the natural choice for removal.

How do you feel about dropping support for this configuration setting?

**Comment by untitaker** [comment]
:+1:

**Comment by geier** [comment]
I'm not a fan of this suggestion. It adds hardly any complexity and I
can think of use cases were one would not want to use the same calendar
color on each device.

Quoting Hugo Osvaldo Barrera (2016-03-05 09:43:17)

**Comment by hobarrera** [comment]
> I can think of use cases were one would not want to use the same calendar color on each device.

You can avoid syncing colours, since it's a separate vdirsyncer command (`vdirsyncer metasync`). Just avoid syncing them. :)

**Comment by hobarrera** [comment]
bump? Can we move forward with this, or just drop the idea?

**Comment by geier** [comment]
Sorry, I'm in favor of dropping it. I see minimal benefit (we really would not be able to delete much code) and loose potential valuable customization features.
