### ISSUE TITLE
Export an event

### ISSUE THREAD

**Issue by jasonwryan** [geier/khal#43]
It would be great to be able to select an event and then export it as a list of space separated fields (sort of a reverse `--new`) to stdout so that it could be scripted to send to an email client as a sort of rudimentary invitation. 

This would complete the calendaring "lifecycle".

**Comment by fpytloun** [comment]
I would also welcome this export feature.
Maybe extend it to sending invitations directly (which is my use-case), for example invite people in event view. Uppon save, open mail client (eg. Mutt, maybe just execute configurable command) with new mail and attached ICS.
It probably shouldn't be so difficult to implement.

**Comment by geier** [comment]
just adding an events as an attachement to an email is easy, implementing (parts of ) RFC5546 not so much. Butt I'll see if we can do it in two parts. Also see #132

**Comment by geier** [comment]
events can now be exportet from ikhal, see #306
