### ISSUE TITLE
ikhal: make it look prettier

### ISSUE THREAD

**Issue by geier** [geier/khal#65]

**Comment by mathstuf** [comment]
I wouldn't something with inspiration from [wyrd](http://pessimization.com/software/wyrd/):

![screenshot](http://pessimization.com/software/wyrd/screenshot.png)

**Comment by geier** [comment]
thanks, there are some good ideas in this screenshot alone.

**Comment by geier** [comment]
would you consider this as prettier than the current state?
 
        ┌──────────────────────────┐┌───────────────────────────────────────────────────┐
        │        June 2013         ││                                                   │
        │                          ││      Today                                        │
        │ Mo Tu We Th Fr Sa Su  w# ││ 1000-1200 Forschungs-Seminar                      │
        │ 27 28 29 30 31  1  2  22 ││ 1345-1745 Physik-Praktikum                        │
        │  3  4  5  6  7  8  9  23 ││ 1900-2100 PyCologne                               │
        │ 10 11 12 13 14 15 16  24 ││       Tomorrow                                    │
        │ 17 18 19 20 21 22 23  25 ││ ★ Max Mustermann                                  │
        │ 24 25 26 27 28 29 30  26 ││ ⊢ Dynamic Days Europe                             │
        │                          ││ 0800-0900 Zahnarzt                                │
        │                          ││ 1900-2100 Grillen bei Sonnenschein                │
        │                          ││       04.06.2013                                  │
        │                          ││ − Dynamic Days Europe                             │
        │                          │└───────────────────────────────────────────────────┘
        │                          │╔═══════════════════════════════════════════════════╗
        │                          │║Title: Forschungs-Seminar                          ║
        │                          │║ Cal:   Work                                       ║
        │                          │║ Time:  05.06. 10:00 - 05.06. 12:00                ║
        │                          │║ Zone:  Berlin/Germany                             ║
        │                          │║ Place: HISKP Seminarraum 3                        ║
        │                          │║ Notes: Rechner nicht vergessen,                   ║
        │                          │║        wird interaktiver Workshop                 ║
        │                          │║                                                   ║
        │                          │║                                                   ║
        │                          │║ <1 attachment>                                    ║
        └──────────────────────────┘╚═══════════════════════════════════════════════════╝
        n new app., tab switch panes, m modify, a see attachment, q quit

**Comment by mathstuf** [comment]
Yes, this would be better. I think I'd rather the month frame to be top-left rather than full-left. Lots of empty space there.

**Comment by protist** [comment]
The one thing that is preventing me from using khal is the lack of proportional times. In the wyrd screenshot, you can quickly see there is a block from 10 am to 6 pm. You can immediately see that this about four times as long as the next appointment. And you can visually see a free hour gap between the two appointments.

This information is quite easy to parse visually, and IMO reading it from an "agenda"-like list is much more difficult. Ideally I'd love to have this kind of display in a week view. Events would be abbreviated if necessary, and perhaps a popup box with the full information.

**Comment by geier** [comment]
I consider it pretty enough for now. Proportional times are another thing though, feel free to open a new issue.

**Comment by protist** [comment]
Yes, I agree that's it's pretty at the moment! Would you like me to open another issue, since proportional times are partially encompassed by issue #251 anyway? (I'd also love to see something similar for <7 days, but I mention that in the other issue.)

**Comment by geier** [comment]
Sure, feel free to open another issues. I imagine that once we have proportional times, the other variants are implemented rather quickly.
