### ISSUE TITLE
Better support for recurrent events

### ISSUE THREAD

**Issue by geier** [geier/khal#68]
- [x] EXDATE
- [x] RDATE with DATE and DATE-TIME values
- [ ] RDATE with PERIOD
- [ ] RECURRENCE-ID (see #95 for example)
- [ ] RECURRENCE-ID;RANGE=THISANDFUTURE:19980401T133000Z

**Comment by untitaker** [comment]
This is mostly done, the rest is documented in https://github.com/geier/khal/issues/152

**Comment by whodevil** [comment]
Awesome.

**Comment by geier** [comment]
@whodevil please report any error you might encounter
